
$font = Monospace

general {
    hide_cursor = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 0, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 2, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
}

input-field {
    monitor = HDMI-A-2
    size = 15%, 15%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill
 
    outer_color = rgba(33ccff00) rgba(00ff9900) 45deg
    check_color = rgba(00ff9900) rgba(ff663300) 120deg
    fail_color = rgba(ff663300) rgba(ff006600) 40deg

    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    rounding = 100

    font_family = $font
    placeholder_text =  
    fail_text = incorrect password

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    dots_size = 0.3
    dots_spacing = .3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor = HDMI-A-2
    text = $TIME12 # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

## DATE
label {
    monitor = HDMI-A-2
    font_size = 25
    #text = cmd[update:60000] date+"%A, %d %B" # update every 60 seconds
    #text = cmd[update:60000],date '+%Y'#'%A, %d %B' # update every 60 seconds
    
    text = cmd[update:60000] date +"%A, %B %d" # update every 60 seconds
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}

# Tampered
label {
    monitor = DP-2
    font_size = 10
    text = $FAIL 
    font_family = $font 

    position = -30, -30
    halign = right
    valign = top
}

## Bonsai
#label {
#    monitor = HDMI-A-2
#    font_size = 1
#    #text = cmd[update:60000] date+"%A, %d %B" # update every 60 seconds
#    #text = cmd[update:60000],date '+%Y'#'%A, %d %B' # update every 60 seconds
#    
#    text = cmd[update:60000] cbonsai -p | sed -r "s/\x1B\[[0-9;]*[A-Za-z]//g"
#    #text = "Hello world"
#    font_family = $font
#
#    position = -0, -0
#    halign = left
#    valign = top
#}

